'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class About

    '''<summary>
    '''UserMeals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserMeals As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''lstCurrentRecipes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstCurrentRecipes As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''txtAddToMeal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddToMeal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnAddRecipeSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddRecipeSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LstSearchResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LstSearchResults As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''btnAddToMeal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddToMeal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtMealName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMealName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnAddMeal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddMeal As Global.System.Web.UI.WebControls.Button
End Class
